#!/usr/bin/env bash
# This script does some stuff

delete()
{
    rm /var/run/myscript.pid
    exit
}

touch /var/run/myscript.pid
while :
  do
    trap 'delete' 15
    trap 'echo "Y U no love me?!"' 2
    trap 'rm -r /var/run/myscript.pid' 3
    echo "To infinity and beyond"
    sleep 2
  done