#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
min=1
while ((hour <= 12))
do
    echo "Hour: $hour"
    while ((min <= 59))
    do
        echo $min
        ((min++))
    done
    min=1
    ((hour++))
done